name: Sync Fork

on:
  schedule:
    - cron: '00 00 * * *' # Every day at midnight UTC
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: SignTools
          merge_method: rebase
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_approve: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
